## T. Sneha Reddy
## AP19110010124, CSE
### DAY-13 Task(21-06-2021)

***TASK***:
Create arrays with different numpy data types. *Numpy has 11 Datatypes and the characters used to represent them are:

1.integer - i   
2.boolean - b  
3.unsigned integer - u  
4.float - f  
5.complex float - c  
6.timedelta - m  
7.datatime - M  
8.object - O  
9.string - S  
10.unicode string - U  
11.fixed chunk of memory for other type (void) - V  

In [1]:
import numpy as np

1.Integer type

In [2]:
arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


2.Boolean type

In [3]:
arr = np.array([1, 2, 3, 4], dtype='bool')

print(arr)
print(arr.dtype)

[ True  True  True  True]
bool


3.Unsigned integer type

In [4]:
arr = np.array([1, 2, 3, 4], dtype=np.uintc)

print(arr)
print(arr.dtype)

[1 2 3 4]
uint32


4.Float type

In [5]:
arr = np.array([1, 2, 3, 4], dtype='f')

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


5.Complex float type

In [6]:
arr = np.array([1, 2, 3, 4], dtype=np.csingle)

print(arr)
print(arr.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex64


6.Timedelta type

In [9]:
a=np.timedelta64(3,'D')
print(a)
a.dtype

3 days


dtype('<m8[D]')

7.Data time type

In [8]:
arr=np.array(['2005-02-25','2005-02-22','2006-03-25'],dtype='M')
print(arr)
print(arr.dtype)

['2005-02-25' '2005-02-22' '2006-03-25']
datetime64[D]


8.Object type

In [10]:
arr = np.array([1, 2, 3, 4], dtype='O')

print(arr)
print(arr.dtype)

[1 2 3 4]
object


9.String type

In [13]:
arr = np.array(["BTS","TXT","NCT"], dtype='S')

print(arr)
print(arr.dtype)

[b'BTS' b'TXT' b'NCT']
|S3


10.Unicode string type

In [14]:
a=np.array([u'\u0394', u'\265Z', u'\265F', u'\u2202r'])
print(a)
print(a.dtype)

['Δ' 'µZ' 'µF' '∂r']
<U2


11.void

In [15]:
a=np.array([],dtype='V')
print(a)
print(a.dtype)

[]
|V8
